import styles from "../../styles/Home.module.css";
import Head from "next/head";

const Login = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next CRUD AUTH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Login</h1>

        <input
          placeholder="Email"
          className={styles.inputBox}
          type="email"
        />
        <input
          placeholder="Password"
          className={styles.inputBox}
          type="password"
        />

        <button className={styles.button} >
          Sign In
        </button>
        <hr />
        <button className={styles.googleAlt} >
          Sign Up with Google
        </button>
        <hr />
        <button className={styles.googleAlt}>
          Sign Up with Github
        </button>
      </main>
    </div>
  );
};

export default Login;
